Parameters:
  Subnet:
    Type: String
    Default: subnet-9388dedb
  InstanceType:
    Type: String
    Default: t2.small
  KeyName:
    Type: String
    Default: _20210420_personal
  SecurityGroup:
    Type: String
    Default: sg-029e6de661f5712bb
  ImageID: 
    Type: String
    Default: ami-0ffea00000f287d30
Resources:
  AnsibleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: AnsibleEC2

  Target1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: Target1
  Target2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: Target2
  Target3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID 
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: Target3