---
- name: download file example
  hosts: all

  tasks:
  - name: get jira file
    get_url:
      url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.5.1-x64.bin
      dest: /tmp/atlassian-jira-software-8.5.1-x64.bin
      mode: '0440'
